DELETE FROM `admin_config`
WHERE `key` IN (
	'MODEL_1_FLOW_ID',
	'MODEL_1_COMPONENT_ID',
	'MODEL_2_FLOW_ID',
	'MODEL_2_COMPONENT_ID',
	'LANGFLOW_API_URL',
	'LANGFLOW_API_KEY',
	'LANGFLOW_FLOW_ID',
	'LANGFLOW_WEBHOOK_SECRET'
);
