// Every enqueue wakes the worker.
//
// The live failure this file guards: a job sat `queued` 212 seconds past its
// own backoff gate, and a `.txt` upload arrived in the middle of that wait and
// did not unstick it — the direct-text path settles inline and used to return
// before the `wakeExtractionWorker()` at the bottom of the function. The same
// hole exists on every early return: a dedupe hit, an unsupported type. None of
// them leaves a job of its OWN queued, which is not the same thing as there
// being nothing to do.
//
// The wake itself is a no-op under vitest by design (a test that uploaded a
// file would otherwise drain with the real extractor registry), so what these
// assert is that the call was MADE.

import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { Artifact } from "$lib/server/services/knowledge/types";
import {
	createLedgerFixture,
	type LedgerFixture,
} from "./testing/ledger-fixtures";

type Intake = typeof import("./intake");
type Worker = typeof import("./worker-runner");

let fixture: LedgerFixture;
let intake: Intake;
let worker: Worker;
let storageDir: string;
const userId = "user-1";

beforeEach(async () => {
	fixture = createLedgerFixture("intake");
	fixture.seedUser(userId);
	storageDir = await mkdtemp(join(tmpdir(), "alfyai-intake-"));

	process.env.DATABASE_PATH = fixture.dbPath;
	vi.resetModules();
	intake = await import("./intake");
	worker = await import("./worker-runner");
	worker.resetExtractionWorkerForTests();
});

afterEach(async () => {
	worker.resetExtractionWorkerForTests();
	fixture.cleanup();
	await rm(storageDir, { recursive: true, force: true });
});

function wakes(): number {
	return worker.inspectExtractionSchedulerForTests().wakeRequests;
}

async function storedArtifact(
	name: string,
	mimeType: string,
	contents = "some text",
): Promise<Artifact> {
	const absolute = join(storageDir, name);
	await writeFile(absolute, contents, "utf8");
	const id = fixture.seedArtifact({
		userId,
		name,
		mimeType,
		storagePath: relative(process.cwd(), absolute),
		sizeBytes: contents.length,
	});
	return {
		id,
		userId,
		name,
		mimeType,
		sizeBytes: contents.length,
	} as Artifact;
}

describe("startUploadExtraction", () => {
	it("wakes on the inline direct-text path that settles inside the request", async () => {
		const artifact = await storedArtifact("notes.txt", "text/plain");

		const dto = await intake.startUploadExtraction({
			userId,
			conversationId: null,
			artifact,
			inlineBudgetMs: 5000,
		});

		expect(dto.status).toBe("succeeded");
		expect(wakes()).toBeGreaterThan(0);
	});

	it("wakes when the job is left queued for the worker", async () => {
		const artifact = await storedArtifact("report.pdf", "application/pdf");

		const dto = await intake.startUploadExtraction({
			userId,
			conversationId: null,
			artifact,
		});

		expect(dto.status).toBe("queued");
		expect(wakes()).toBeGreaterThan(0);
	});

	it("wakes on a dedupe hit that is born succeeded", async () => {
		const artifact = await storedArtifact("dupe.pdf", "application/pdf");
		const normalizedArtifactId = fixture.seedArtifact({
			userId,
			type: "normalized_document",
			name: "dupe.pdf.md",
		});

		const dto = await intake.startUploadExtraction({
			userId,
			conversationId: null,
			artifact,
			existingNormalizedArtifactId: normalizedArtifactId,
		});

		expect(dto.status).toBe("succeeded");
		expect(wakes()).toBeGreaterThan(0);
	});

	it("wakes on an unsupported type that is born failed", async () => {
		const artifact = await storedArtifact("clip.mp4", "video/mp4");

		const dto = await intake.startUploadExtraction({
			userId,
			conversationId: null,
			artifact,
		});

		expect(dto.status).toBe("failed");
		expect(wakes()).toBeGreaterThan(0);
	});
});

describe("startGeneratedFileReadback", () => {
	async function seedGeneratedFile(name: string, mimeType: string) {
		fixture.seedConversation("conv-1", userId);
		fixture.sqlite
			.prepare(
				`INSERT INTO messages (id, conversation_id, role, content, created_at)
				 VALUES ('msg-1', 'conv-1', 'assistant', 'here', unixepoch())`,
			)
			.run();
		const absolute = join(storageDir, name);
		await writeFile(absolute, "generated bytes", "utf8");
		fixture.sqlite
			.prepare(
				`INSERT INTO chat_generated_files
				 (id, conversation_id, assistant_message_id, user_id, filename, mime_type, size_bytes, storage_path, created_at)
				 VALUES ('gen-1', 'conv-1', 'msg-1', ?, ?, ?, 15, ?, unixepoch())`,
			)
			.run(
				userId,
				name,
				mimeType,
				relative(join(process.cwd(), "data", "chat-files"), absolute),
			);
	}

	it("wakes when the readback job is queued", async () => {
		await seedGeneratedFile("generated.pdf", "application/pdf");

		const dto = await intake.startGeneratedFileReadback({
			userId,
			conversationId: "conv-1",
			chatGeneratedFileId: "gen-1",
			fileName: "generated.pdf",
			mimeType: "application/pdf",
			sizeBytes: 15,
		});

		expect(dto.status).toBe("queued");
		expect(wakes()).toBeGreaterThan(0);
	});

	it("wakes even when the readback is refused outright", async () => {
		await seedGeneratedFile("clip.mp4", "video/mp4");

		const dto = await intake.startGeneratedFileReadback({
			userId,
			conversationId: "conv-1",
			chatGeneratedFileId: "gen-1",
			fileName: "clip.mp4",
			mimeType: "video/mp4",
			sizeBytes: 15,
		});

		expect(dto.status).toBe("failed");
		expect(wakes()).toBeGreaterThan(0);
	});
});
