// Readback: what the ledger writes back onto a generated file's artifact.
//
// Runs against a real migrated database rather than a mocked one, because the
// two things worth proving here — that the artifact ends up byte-identical to
// what the old inline extraction produced, and that its chunks are rebuilt from
// the new text — are both statements about rows.

import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { eq } from "drizzle-orm";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import * as schema from "$lib/server/db/schema";
import { createFakeExtractor } from "./testing/fake-extractor";
import {
	createLedgerFixture,
	type LedgerFixture,
} from "./testing/ledger-fixtures";

const queueRefresh = vi.hoisted(() => vi.fn());
vi.mock("$lib/server/services/semantic-embedding-refresh", () => ({
	queueArtifactSemanticEmbeddingRefresh: queueRefresh,
}));

type Readback = typeof import("./readback");
type Worker = typeof import("./worker-runner");
type Ledger = typeof import("./job-ledger");

let fixture: LedgerFixture;
let readback: Readback;
let worker: Worker;
let ledger: Ledger;
let storageDir: string;

const userId = "user-1";
const conversationId = "conv-1";
const chatFileId = "gen-1";

/** The wrapper `syncGeneratedFilesToMemory` writes before any text exists. */
const WRAPPER_HEAD = [
	"Generated file: report.pdf",
	"File type: application/pdf",
	"Chat file id: gen-1",
	"Generated in conversation: conv-1",
	"Generated file version: v1",
	"",
	"Assistant response context:",
	"Here is the report.",
].join("\n");

const PENDING_WRAPPER = `${WRAPPER_HEAD}\n\nExtracted file content: No readable text could be extracted from this file. Use the filename, file type, and surrounding chat context when continuing it.`;

function seedGeneratedArtifact(contentText = PENDING_WRAPPER): string {
	const id = "artifact-1";
	fixture.db
		.insert(schema.artifacts)
		.values({
			id,
			userId,
			conversationId,
			type: "generated_output",
			name: "report.pdf",
			mimeType: "text/markdown",
			extension: "md",
			sizeBytes: Buffer.byteLength(contentText, "utf8"),
			contentText,
			summary: "Generated file: report.pdf",
			metadataJson: JSON.stringify({
				generatedFile: true,
				originalChatFileId: chatFileId,
				generatedFilename: "report.pdf",
				versionNumber: 1,
			}),
			createdAt: new Date("2026-09-20T09:00:00.000Z"),
			updatedAt: new Date("2026-09-20T09:00:00.000Z"),
		})
		.run();
	return id;
}

async function seedStoredChatFile(filename = "report.pdf"): Promise<void> {
	const absolute = join(storageDir, filename);
	await writeFile(absolute, "generated bytes", "utf8");
	fixture.sqlite
		.prepare(
			`INSERT INTO chat_generated_files
			 (id, conversation_id, assistant_message_id, user_id, filename, mime_type, size_bytes, storage_path, created_at)
			 VALUES (?, ?, 'msg-1', ?, ?, 'application/pdf', 15, ?, unixepoch())`,
		)
		.run(
			chatFileId,
			conversationId,
			userId,
			filename,
			relative(join(process.cwd(), "data", "chat-files"), absolute),
		);
}

function readArtifact(id: string) {
	return fixture.db
		.select()
		.from(schema.artifacts)
		.where(eq(schema.artifacts.id, id))
		.all()[0];
}

function readChunks(artifactId: string) {
	return fixture.db
		.select()
		.from(schema.artifactChunks)
		.where(eq(schema.artifactChunks.artifactId, artifactId))
		.all();
}

beforeEach(async () => {
	fixture = createLedgerFixture("readback");
	fixture.seedUser(userId);
	fixture.seedConversation(conversationId, userId);
	fixture.sqlite
		.prepare(
			`INSERT INTO messages (id, conversation_id, role, content, created_at)
			 VALUES ('msg-1', ?, 'assistant', 'Here is the report.', unixepoch())`,
		)
		.run(conversationId);

	storageDir = await mkdtemp(join(tmpdir(), "alfyai-readback-"));
	process.env.DATABASE_PATH = fixture.dbPath;
	vi.resetModules();
	queueRefresh.mockReset();
	worker = await import("./worker-runner");
	ledger = await import("./job-ledger");
	worker.resetExtractionWorkerForTests();
	readback = await import("./readback");
});

afterEach(async () => {
	fixture.cleanup();
	await rm(storageDir, { recursive: true, force: true });
	vi.restoreAllMocks();
});

describe("applyExtractedTextToGeneratedFileMemoryContent", () => {
	it("swaps the pending section for the text and leaves the head alone", () => {
		const next = readback.applyExtractedTextToGeneratedFileMemoryContent(
			PENDING_WRAPPER,
			"Quarterly revenue grew.",
		);

		expect(next).toBe(
			`${WRAPPER_HEAD}\n\nExtracted file content:\nQuarterly revenue grew.`,
		);
	});

	it("replaces a section that already carries text", () => {
		const withText = `${WRAPPER_HEAD}\n\nExtracted file content:\nfirst pass`;

		expect(
			readback.applyExtractedTextToGeneratedFileMemoryContent(
				withText,
				"second pass",
			),
		).toBe(`${WRAPPER_HEAD}\n\nExtracted file content:\nsecond pass`);
	});

	it("appends a section to a wrapper that has none", () => {
		expect(
			readback.applyExtractedTextToGeneratedFileMemoryContent(
				"Generated file: report.pdf",
				"body",
			),
		).toBe("Generated file: report.pdf\n\nExtracted file content:\nbody");
	});

	// `read_generated_file` splits on "\nExtracted file content:\n"; the empty
	// shape deliberately does not contain it, so a file with no text falls back
	// to the whole wrapper instead of answering "empty document".
	it("writes the no-text sentence when there is nothing to write", () => {
		expect(
			readback.applyExtractedTextToGeneratedFileMemoryContent(
				`${WRAPPER_HEAD}\n\nExtracted file content:\nfirst pass`,
				null,
			),
		).toBe(PENDING_WRAPPER);
	});
});

describe("completeGeneratedFileReadback", () => {
	it("patches the artifact, resizes it and rebuilds its chunks", async () => {
		const artifactId = seedGeneratedArtifact();
		// A chunk cut from the pending wrapper. It has to go: a chunk set that
		// still describes the old text is exactly what breaks retrieval offsets.
		fixture.db
			.insert(schema.artifactChunks)
			.values({
				id: "stale-chunk",
				artifactId,
				userId,
				conversationId,
				chunkIndex: 0,
				contentText: "stale pending chunk",
				tokenEstimate: 4,
			})
			.run();
		const extracted = `Quarterly revenue grew by nine percent. ${"Detail sentence. ".repeat(330)}`;

		const result = await readback.completeGeneratedFileReadback({
			userId,
			conversationId,
			chatGeneratedFileId: chatFileId,
			text: extracted,
			pageCount: 4,
		});

		expect(result).toEqual({ artifactId, chunksTruncated: false });
		const row = readArtifact(artifactId);
		expect(row.contentText).toBe(
			`${WRAPPER_HEAD}\n\nExtracted file content:\n${extracted.trim()}`,
		);
		expect(row.sizeBytes).toBe(
			Buffer.byteLength(row.contentText ?? "", "utf8"),
		);
		const chunks = readChunks(artifactId);
		expect(chunks.length).toBeGreaterThan(0);
		expect(chunks.map((chunk) => chunk.id)).not.toContain("stale-chunk");
		expect(chunks[0].contentText).toContain("Quarterly revenue grew");
		expect(queueRefresh).toHaveBeenCalledTimes(1);
		// Deliberately not stored: a page count on a generated file would be a new
		// fact in the attachment UI that the inline path never produced.
		expect(row.metadataJson).not.toContain("pageCount");
	});

	it("refuses when the artifact is gone, without retrying forever", async () => {
		await expect(
			readback.completeGeneratedFileReadback({
				userId,
				conversationId,
				chatGeneratedFileId: "missing-file",
				text: "text",
				pageCount: null,
			}),
		).rejects.toMatchObject({ code: "internal", retryable: false });
	});

	it("never writes onto another user's generated file", async () => {
		const artifactId = seedGeneratedArtifact();
		fixture.seedUser("user-2");

		await expect(
			readback.completeGeneratedFileReadback({
				userId: "user-2",
				conversationId,
				chatGeneratedFileId: chatFileId,
				text: "stolen",
				pageCount: null,
			}),
		).rejects.toMatchObject({ code: "internal" });
		expect(readArtifact(artifactId).contentText).toBe(PENDING_WRAPPER);
	});
});

describe("the registered sink", () => {
	async function enqueueReadback(): Promise<string> {
		const { job } = await ledger.enqueueExtractionJob({
			userId,
			conversationId,
			origin: "generated_file_readback",
			intakeRoute: "mineru",
			fileName: "report.pdf",
			mimeType: "application/pdf",
			sizeBytes: 15,
			chatGeneratedFileId: chatFileId,
			priority: 10,
		});
		return job.id;
	}

	// Importing the module is the registration. A readback job queued before a
	// restart is claimed during server init, long before anything calls into
	// chat-files, so a sink that registered on first use would lose it.
	it("is installed by importing the module, with no other wiring", async () => {
		const artifactId = seedGeneratedArtifact();
		await seedStoredChatFile();
		const jobId = await enqueueReadback();

		const result = await worker.executeNextExtractionJob({
			workerId: "w1",
			resolveExtractor: () =>
				createFakeExtractor({
					steps: [{ kind: "succeed", text: "Extracted PDF body." }],
				}),
		});

		expect(result).toEqual({ jobId, status: "succeeded" });
		const row = await ledger.getExtractionJobRow(jobId);
		expect(row?.normalizedArtifactId).toBe(artifactId);
		expect(readArtifact(artifactId).contentText).toBe(
			`${WRAPPER_HEAD}\n\nExtracted file content:\nExtracted PDF body.`,
		);
	});

	it("survives a re-registration, as a double import or an HMR reload does", async () => {
		const artifactId = seedGeneratedArtifact();
		await seedStoredChatFile();
		await enqueueReadback();
		readback.ensureGeneratedFileReadbackSinkRegistered();
		readback.ensureGeneratedFileReadbackSinkRegistered();

		const result = await worker.executeNextExtractionJob({
			workerId: "w1",
			resolveExtractor: () =>
				createFakeExtractor({ steps: [{ kind: "succeed", text: "once" }] }),
		});

		expect(result?.status).toBe("succeeded");
		expect(readArtifact(artifactId).contentText).toBe(
			`${WRAPPER_HEAD}\n\nExtracted file content:\nonce`,
		);
	});

	// Deletion race: the chat file (and with it the job, by cascade) goes away
	// while the job is queued. Nothing is claimed, nothing throws, nothing loops.
	it("ends cleanly when the generated file is deleted before the worker gets to it", async () => {
		seedGeneratedArtifact();
		await seedStoredChatFile();
		const jobId = await enqueueReadback();

		fixture.sqlite
			.prepare("DELETE FROM chat_generated_files WHERE id = ?")
			.run(chatFileId);

		expect(await ledger.getExtractionJobRow(jobId)).toBeNull();
		await expect(
			worker.executeNextExtractionJob({
				workerId: "w1",
				resolveExtractor: () =>
					createFakeExtractor({ steps: [{ kind: "succeed" }] }),
			}),
		).resolves.toBeNull();
	});

	// The bytes are gone but the row survived (a failed unlink, a restored DB).
	// The job has to end, not spin.
	it("fails the job once when the stored bytes are gone", async () => {
		seedGeneratedArtifact();
		await seedStoredChatFile();
		const jobId = await enqueueReadback();
		await rm(join(storageDir, "report.pdf"), { force: true });

		const result = await worker.executeNextExtractionJob({
			workerId: "w1",
			resolveExtractor: () =>
				createFakeExtractor({
					steps: [{ kind: "throw", code: "unsupported_type" }],
				}),
		});

		expect(result?.status).toBe("failed");
		const row = await ledger.getExtractionJobRow(jobId);
		expect(row?.status).toBe("failed");
		expect(row?.attemptCount).toBe(1);
	});
});
