import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { chromium, type Page } from "playwright";

type ConversationDetail = {
	fileProductionJobs?: FileProductionJob[];
};

type FileProductionJob = {
	id: string;
	title?: string;
	status?: string;
	error?: { code?: string; message?: string; retryable?: boolean } | null;
	files?: ProducedFile[];
};

type ProducedFile = {
	id: string;
	filename: string;
	mimeType: string | null;
	sizeBytes: number;
	downloadUrl: string;
};

type FileTypeCase = {
	label: string;
	sourceMode: "document_source" | "program";
	requestedType: string;
	expectedExtension: string;
	expectedMimePrefix: string;
	body: (conversationId: string) => Record<string, unknown>;
};

const baseUrl = process.env.LIVE_AI_BASE_URL ?? "https://ai.alfydesign.com";
const email = process.env.LIVE_AI_EMAIL;
const password = process.env.LIVE_AI_PASSWORD;
const headless = process.env.LIVE_AI_HEADLESS !== "false";
const keepConversation = process.env.LIVE_AI_KEEP_CONVERSATION === "true";
const timeoutMs = Number(process.env.LIVE_AI_TIMEOUT_MS ?? 240_000);
const outputDir =
	process.env.LIVE_AI_OUTPUT_DIR ??
	path.join(
		process.cwd(),
		"test-results",
		`live-file-production-types-${new Date().toISOString().replace(/[:.]/g, "-")}`,
	);

function requireEnv(name: string, value: string | undefined): string {
	if (!value) throw new Error(`${name} is required`);
	return value;
}

function apiPath(value: string): string {
	return new URL(value, baseUrl).toString();
}

async function authenticatedFetch(
	page: Page,
	url: string,
	init: RequestInit = {},
): Promise<Response> {
	const headers = new Headers(init.headers);
	const cookies = await page.context().cookies(baseUrl);
	const cookieHeader = cookies
		.map((cookie) => `${cookie.name}=${cookie.value}`)
		.join("; ");
	if (cookieHeader) headers.set("Cookie", cookieHeader);
	return fetch(apiPath(url), { ...init, headers });
}

async function apiJson<T>(
	page: Page,
	url: string,
	init?: RequestInit,
): Promise<T> {
	const response = await authenticatedFetch(page, url, init);
	const text = await response.text();
	if (!response.ok) {
		throw new Error(`HTTP ${response.status} from ${url}: ${text}`);
	}
	return JSON.parse(text) as T;
}

async function login(page: Page) {
	await page.goto(apiPath("/login"), { waitUntil: "domcontentloaded" });
	const response = await page.request.post(apiPath("/api/auth/login"), {
		data: {
			email: requireEnv("LIVE_AI_EMAIL", email),
			password: requireEnv("LIVE_AI_PASSWORD", password),
		},
		headers: { "Content-Type": "application/json" },
	});
	if (!response.ok()) {
		throw new Error(`Login failed with HTTP ${response.status()}`);
	}
	await page.goto(apiPath("/"), { waitUntil: "domcontentloaded" });
}

async function createConversation(page: Page): Promise<string> {
	const payload = await apiJson<{ id: string }>(page, "/api/conversations", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({
			title: `Live file type sweep ${new Date().toISOString()}`,
			projectId: null,
		}),
	});
	return payload.id;
}

async function deleteConversation(page: Page, conversationId: string) {
	const response = await authenticatedFetch(
		page,
		`/api/conversations/${encodeURIComponent(conversationId)}`,
		{ method: "DELETE" },
	);
	if (!response.ok) {
		throw new Error(
			`Failed to delete conversation ${conversationId}: HTTP ${response.status} ${await response.text()}`,
		);
	}
}

async function getConversationDetail(
	page: Page,
	conversationId: string,
): Promise<ConversationDetail> {
	return apiJson<ConversationDetail>(
		page,
		`/api/conversations/${encodeURIComponent(conversationId)}`,
	);
}

async function pollForJob(
	page: Page,
	conversationId: string,
	jobId: string,
): Promise<FileProductionJob> {
	const deadline = Date.now() + timeoutMs;
	let lastJob: FileProductionJob | null = null;
	while (Date.now() < deadline) {
		const detail = await getConversationDetail(page, conversationId);
		lastJob =
			detail.fileProductionJobs?.find((candidate) => candidate.id === jobId) ??
			lastJob;
		if (
			lastJob &&
			["succeeded", "failed", "cancelled"].includes(String(lastJob.status ?? ""))
		) {
			return lastJob;
		}
		await page.waitForTimeout(1500);
	}
	throw new Error(
		`Timed out waiting for job ${jobId}; last status=${lastJob?.status ?? "missing"}`,
	);
}

const documentSource = {
	version: 1,
	template: "alfyai_standard_report",
	title: "Live File Type Report",
	blocks: [
		{ type: "heading", level: 2, text: "Summary" },
		{
			type: "paragraph",
			text: "This file was generated by the live file production type sweep.",
		},
		{ type: "list", style: "bullet", items: ["Alpha", "Beta", "Gamma"] },
	],
};

function documentSourceBody(type: string, conversationId: string) {
	return {
		conversationId,
		idempotencyKey: `live-type:${type}:${crypto.randomUUID()}`,
		requestTitle: `Live document ${type.toUpperCase()}`,
		sourceMode: "document_source",
		requestedOutputs: [{ type }],
		documentIntent: "live file type sweep document",
		documentSource,
	};
}

function programBody(
	type: string,
	conversationId: string,
	filename: string,
	language: "python" | "javascript",
	sourceCode: string,
) {
	return {
		conversationId,
		idempotencyKey: `live-type:${type}:${crypto.randomUUID()}`,
		requestTitle: `Live program ${type.toUpperCase()}`,
		sourceMode: "program",
		requestedOutputs: [{ type }],
		documentIntent: "live file type sweep program artifact",
		program: { language, sourceCode, filename },
	};
}

const cases: FileTypeCase[] = [
	{
		label: "document-pdf",
		sourceMode: "document_source",
		requestedType: "pdf",
		expectedExtension: ".pdf",
		expectedMimePrefix: "application/pdf",
		body: (conversationId) => documentSourceBody("pdf", conversationId),
	},
	{
		label: "document-docx",
		sourceMode: "document_source",
		requestedType: "docx",
		expectedExtension: ".docx",
		expectedMimePrefix:
			"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
		body: (conversationId) => documentSourceBody("docx", conversationId),
	},
	{
		label: "document-html",
		sourceMode: "document_source",
		requestedType: "html",
		expectedExtension: ".html",
		expectedMimePrefix: "text/html",
		body: (conversationId) => documentSourceBody("html", conversationId),
	},
	{
		label: "program-csv",
		sourceMode: "program",
		requestedType: "csv",
		expectedExtension: ".csv",
		expectedMimePrefix: "text/csv",
		body: (conversationId) =>
			programBody(
				"csv",
				conversationId,
				"live-type.csv",
				"python",
				`from pathlib import Path\nPath('/output/live-type.csv').write_text('name,value\\nalpha,1\\n', encoding='utf-8')`,
			),
	},
	{
		label: "program-json",
		sourceMode: "program",
		requestedType: "json",
		expectedExtension: ".json",
		expectedMimePrefix: "application/json",
		body: (conversationId) =>
			programBody(
				"json",
				conversationId,
				"live-type.json",
				"python",
				`from pathlib import Path\nPath('/output/live-type.json').write_text('{"name":"alpha","value":1}\\n', encoding='utf-8')`,
			),
	},
	{
		label: "program-txt",
		sourceMode: "program",
		requestedType: "txt",
		expectedExtension: ".txt",
		expectedMimePrefix: "text/plain",
		body: (conversationId) =>
			programBody(
				"txt",
				conversationId,
				"live-type.txt",
				"python",
				`from pathlib import Path\nPath('/output/live-type.txt').write_text('plain text output\\n', encoding='utf-8')`,
			),
	},
	{
		label: "program-markdown",
		sourceMode: "program",
		requestedType: "markdown",
		expectedExtension: ".md",
		expectedMimePrefix: "text/markdown",
		body: (conversationId) =>
			programBody(
				"markdown",
				conversationId,
				"live-type.md",
				"python",
				`from pathlib import Path\nPath('/output/live-type.md').write_text('# Markdown output\\n\\n- alpha\\n- beta\\n', encoding='utf-8')`,
			),
	},
	{
		label: "program-svg",
		sourceMode: "program",
		requestedType: "svg",
		expectedExtension: ".svg",
		expectedMimePrefix: "image/svg+xml",
		body: (conversationId) =>
			programBody(
				"svg",
				conversationId,
				"live-type.svg",
				"python",
				`from pathlib import Path\nPath('/output/live-type.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" width="160" height="80"><rect width="160" height="80" fill="#f4f4f5"/><text x="20" y="45" font-size="18">Live SVG</text></svg>', encoding='utf-8')`,
			),
	},
	{
		label: "program-zip",
		sourceMode: "program",
		requestedType: "zip",
		expectedExtension: ".zip",
		expectedMimePrefix: "application/zip",
		body: (conversationId) =>
			programBody(
				"zip",
				conversationId,
				"live-type.zip",
				"python",
				`from pathlib import Path\nfrom zipfile import ZipFile\nwith ZipFile('/output/live-type.zip', 'w') as z:\n    z.writestr('README.txt', 'zip output')`,
			),
	},
	{
		label: "program-xlsx",
		sourceMode: "program",
		requestedType: "xlsx",
		expectedExtension: ".xlsx",
		expectedMimePrefix:
			"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
		body: (conversationId) =>
			programBody(
				"xlsx",
				conversationId,
				"live-type.xlsx",
				"javascript",
				`
const ExcelJS = require('exceljs');
const workbook = new ExcelJS.Workbook();
workbook.calcProperties.fullCalcOnLoad = true;
const sheet = workbook.addWorksheet('Summary');
sheet.columns = [{ header: 'Metric', key: 'metric' }, { header: 'Value', key: 'value' }];
sheet.addRow({ metric: 'alpha', value: 1 });
await workbook.xlsx.writeFile('/output/live-type.xlsx');
`.trim(),
			),
	},
	{
		label: "program-pptx",
		sourceMode: "program",
		requestedType: "pptx",
		expectedExtension: ".pptx",
		expectedMimePrefix:
			"application/vnd.openxmlformats-officedocument.presentationml.presentation",
		body: (conversationId) =>
			programBody(
				"pptx",
				conversationId,
				"live-type.pptx",
				"javascript",
				`
const pptxgen = require('pptxgenjs');
const pptx = new pptxgen();
const slide = pptx.addSlide();
slide.addText('Live PPTX output', { x: 0.7, y: 0.7, w: 8, h: 0.6, fontSize: 24 });
await pptx.writeFile({ fileName: '/output/live-type.pptx' });
`.trim(),
			),
	},
	{
		label: "program-docx",
		sourceMode: "program",
		requestedType: "docx",
		expectedExtension: ".docx",
		expectedMimePrefix:
			"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
		body: (conversationId) =>
			programBody(
				"docx",
				conversationId,
				"live-type.docx",
				"javascript",
				`
const fs = require('fs');
const { Document, Packer, Paragraph, TextRun } = require('docx');
const doc = new Document({
  sections: [{ children: [new Paragraph({ children: [new TextRun('Live DOCX output')] })] }],
});
fs.writeFileSync('/output/live-type.docx', await Packer.toBuffer(doc));
`.trim(),
			),
	},
	{
		label: "program-odt",
		sourceMode: "program",
		requestedType: "odt",
		expectedExtension: ".odt",
		expectedMimePrefix: "application/vnd.oasis.opendocument.text",
		body: (conversationId) =>
			programBody(
				"odt",
				conversationId,
				"live-type.odt",
				"javascript",
				`
const fs = require('fs');
const JSZip = require('jszip');
const zip = new JSZip();
zip.file('mimetype', 'application/vnd.oasis.opendocument.text', { compression: 'STORE' });
zip.file('content.xml', '<?xml version="1.0" encoding="UTF-8"?><office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"><office:body><office:text><text:p>Live ODT output</text:p></office:text></office:body></office:document-content>');
fs.writeFileSync('/output/live-type.odt', await zip.generateAsync({ type: 'nodebuffer' }));
`.trim(),
			),
	},
];

async function postProduceFile(
	page: Page,
	body: Record<string, unknown>,
): Promise<FileProductionJob> {
	const response = await authenticatedFetch(page, "/api/chat/files/produce", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(body),
	});
	const data = (await response.json()) as { job?: FileProductionJob; error?: string };
	if (!response.ok) {
		return {
			id: data.job?.id ?? "missing-job",
			status: data.job?.status ?? "request_failed",
			error: data.job?.error ?? { message: data.error ?? `HTTP ${response.status}` },
			files: data.job?.files ?? [],
		};
	}
	if (!data.job) throw new Error("produce_file response did not contain job");
	return data.job;
}

async function verifyDownload(
	page: Page,
	file: ProducedFile,
	expected: Pick<FileTypeCase, "expectedExtension" | "expectedMimePrefix">,
) {
	const response = await authenticatedFetch(page, file.downloadUrl);
	const bytes = new Uint8Array(await response.arrayBuffer());
	return {
		ok:
			response.ok &&
			file.filename.endsWith(expected.expectedExtension) &&
			(file.mimeType ?? "").startsWith(expected.expectedMimePrefix) &&
			(response.headers.get("content-type") ?? "").startsWith(
				expected.expectedMimePrefix,
			) &&
			bytes.byteLength > 0,
		status: response.status,
		contentType: response.headers.get("content-type"),
		contentLength: bytes.byteLength,
	};
}

async function main() {
	await mkdir(outputDir, { recursive: true });
	const browser = await chromium.launch({ headless });
	const page = await browser.newPage();
	const results: Array<Record<string, unknown>> = [];
	let conversationId: string | null = null;

	try {
		await login(page);
		conversationId = await createConversation(page);

		for (const testCase of cases) {
			const accepted = await postProduceFile(page, testCase.body(conversationId));
			const terminal =
				accepted.id === "missing-job" || accepted.status === "failed"
					? accepted
					: await pollForJob(page, conversationId, accepted.id);
			const file = terminal.files?.[0] ?? null;
			const download = file
				? await verifyDownload(page, file, testCase)
				: null;
			const ok =
				terminal.status === "succeeded" &&
				Boolean(file) &&
				download?.ok === true;
			results.push({
				label: testCase.label,
				sourceMode: testCase.sourceMode,
				requestedType: testCase.requestedType,
				ok,
				jobId: terminal.id,
				status: terminal.status,
				error: terminal.error ?? null,
				file: file
					? {
							filename: file.filename,
							mimeType: file.mimeType,
							sizeBytes: file.sizeBytes,
						}
					: null,
				download,
			});
		}
	} finally {
		if (conversationId && !keepConversation) {
			await deleteConversation(page, conversationId);
		}
		await browser.close();
	}

	const summary = {
		baseUrl,
		conversationId,
		keptConversation: keepConversation,
		createdAt: new Date().toISOString(),
		results,
		ok: results.every((result) => result.ok === true),
	};
	await writeFile(
		path.join(outputDir, "summary.json"),
		JSON.stringify(summary, null, 2),
	);
	console.log(JSON.stringify(summary, null, 2));
	if (!summary.ok) process.exitCode = 1;
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
